apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-cli.fullname" . }}-cli-cc
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  GOPATH: /opt/gopath
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  FABRIC_LOGGING_SPEC: INFO
  CORE_PEER_ID: {{ .Release.Name }}
  CORE_PEER_ADDRESS: peer1-hlf-peer.peers.svc.cluster.local:7051
  CORE_PEER_LOCALMSPID: {{ .Values.peer.mspID | quote }}
  CORE_PEER_MSPCONFIGPATH: /var/hyperledger/admin_msp
  CORE_PEER_TLS_ENABLED: {{ .Values.peer.tls.server.enabled | quote }}
  CORE_PEER_TLS_CERT_FILE: "/var/hyperledger/tls/server/pair/tls.crt"
  CORE_PEER_TLS_KEY_FILE: "/var/hyperledger/tls/server/pair/tls.key"
  CORE_PEER_TLS_ROOTCERT_FILE: "/var/hyperledger/tls/server/cert/cacert.pem"