apiVersion: v1
description: CouchDB instance for Hyperledger Fabric (these charts are created by AID:Tech and are currently not directly associated with the Hyperledger project)
name: hlf-couchdb
version: 0.0.1
appVersion: 0.4.10
keywords:
  - blockchain
  - hyperledger
  - fabric
  - couchdb
home: http://hyperledger-fabric.readthedocs.io
sources:
  - https://github.com/hyperledger/fabric
maintainers:
  - name: 
    email: 
icon: https://www.hyperledger.org/wp-content/uploads/2018/04/fabric-logo.png
